name: Test

on:
  # manually
  workflow_dispatch:
  ## cron
  #schedule:
  #  - cron: "25 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PostgreSQL source code
        uses: actions/checkout@v2
        with:
          repository: "postgres/postgres"
          ref: "master"

      - name: Checkout pg_bigm source code
        uses: actions/checkout@v2
        with:
          path: postgres/contrib

      - name: make and install PostgreSQL with extentions
        run: >
          cd postgres
          && ./configure --prefix=/var/pghome --enable-debug --enable-cassert
          && make -j 2
          && make install
          && cd contrib/pg_trgm
          && make install
          && cd contrib/pg_bigm
          && make install
          && /var/pghome/bin/initdb -D /var/pgdata --locale=C --encoding=UTF8
          && /var/pghome/bin/pg_ctl -D /var/pgdata -w start

      - name: run test
        run: >
          make USE_PGXS=1 PG_CONFIG=/var/pghome/bin/pg_config installcheck
          make USE_PGXS=1 PG_CONFIG=/var/pghome/bin/pg_config installcheck-trgm
