name: Test

on:
  # manually
  workflow_dispatch:
  ## cron
  #schedule:
  #  - cron: "25 6 * * *"

jobs:
  test:
    strategy:
      matrix:
        branch: [
            master,
            REL_14_STABLE,
            REL_13_STABLE,
            REL_12_STABLE,
            REL_11_STABLE,
            REL_10_STABLE,
            REL9_6_STABLE,
            REL9_5_STABLE,
            REL9_4_STABLE,
            REL9_3_STABLE,
            REL9_2_STABLE,
            REL9_1_STABLE
        ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout PostgreSQL source code
        uses: actions/checkout@v2
        with:
          clean: true
          repository: postgres/postgres
          ref: ${{ matrix.branch }}
          path: postgres

      - name: Checkout pg_bigm source code
        uses: actions/checkout@v2
        with:
          clean: false
          path: postgres/contrib/pg_bigm

      - name: Make and install PostgreSQL
        run: >
          cd postgres
          && ./configure --prefix=$GITHUB_WORKSPACE/pghome --enable-debug --enable-cassert
          && make --quiet -j 2
          && make --quiet install

      - name: Make and install pg_trgm
        run: cd postgres/contrib/pg_trgm && make install

      - name: Make and install pg_bigm
        run: cd postgres/contrib/pg_bigm && make install

      - name: Start PostgreSQL
        run: >
          $GITHUB_WORKSPACE/pghome/bin/initdb -D $GITHUB_WORKSPACE/pgdata --locale=C --encoding=UTF8
          && $GITHUB_WORKSPACE/pghome/bin/pg_ctl -D $GITHUB_WORKSPACE/pgdata -w start

      - name: Run test
        run: >
          cd postgres/contrib/pg_bigm
          && make USE_PGXS=1 PG_CONFIG=$GITHUB_WORKSPACE/pghome/bin/pg_config installcheck
          && make USE_PGXS=1 PG_CONFIG=$GITHUB_WORKSPACE/pghome/bin/pg_config installcheck-trgm
